version: '3.8'

services:
  # Service Backend
  backend:
    build:
      context: ./backend
    container_name: gestion-tickets-backend
    ports:
      - "3001:3001" # Port d'écoute du backend
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
    depends_on:
      - db # Le backend dépend du service de la base de données
    networks:
      - gestion-tickets-network

  # Service Frontend
  frontend:
    build:
      context: ./frontend
    container_name: gestion-tickets-frontend
    ports:
      - "8501:8501" # Port d'écoute du frontend (si c'est une app Streamlit)
    environment:
      - REACT_APP_API_URL=http://backend:3001 # URL du backend à l'intérieur du réseau Docker
    volumes:
      - ./frontend:/app
    depends_on:
      - backend # Le frontend dépend du backend
    networks:
      - gestion-tickets-network

  # Service Base de données MySQL
  db:
    image: mysql:8
    container_name: gestion-tickets-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_tickets_db
    volumes:
      - ./database/init-scripts:/docker-entrypoint-initdb.d # Scripts d'initialisation si nécessaire
    ports:
      - "3307:3306" # Port d'écoute de la base de données
    networks:
      - gestion-tickets-network

networks:
  gestion-tickets-network:
    driver: bridge

volumes:
  db_data:
    driver: local
